// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ProcessPullRequest(arg1) {
  return window['go']['main']['App']['ProcessPullRequest'](arg1);
}
